

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/your_database
#    username: your_username
#    password: your_password
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect


#on Mail deployment you keeep most same hust the host for mail
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookms_db
    username: pratham
    password: pratham
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: localhost
    port:
    username: ali
    password: pm
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: pratham1265775
      expiration: 864000000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ./uploads
  server:
    port: 8080



